DROP TABLE contacttable;
CREATE EXTERNAL TABLE contacttable
(
	
	TransactionCurrencyIdName string,
	PreferredSystemUserIdName string,
	EntityImage_URL string,
	mbs_countryidName string,
	CreatedOnBehalfByName string,
	CreatedByYomiName string,
	MasterContactIdYomiName string,
	PreferredEquipmentIdName string,
	mbs_stateidName string,
	mbs_preferredlanguageidName string,
	PreferredSystemUserIdYomiName string,
	MasterContactIdName string,
	OriginatingLeadIdYomiName string,
	EntityImage_Timestamp bigint ,
	mbs_PartnerIdName string,
	ModifiedByName string,
	ModifiedOnBehalfByName string,
	CreatedOnBehalfByYomiName string,
	EntityImage string ,
	ModifiedOnBehalfByYomiName string,
	PreferredServiceIdName string,
	DefaultPriceLevelIdName string,
	OriginatingLeadIdName string,
	CreatedByName string,
	ModifiedByYomiName string,
	Address1_AddressTypeCode int ,
	Address1_City string,
	Address1_Composite string,
	Address1_Country string,
	Address1_County string,
	Address1_AddressId string ,
	Address1_Fax string,
	Address1_FreightTermsCode int ,
	Address1_Latitude float ,
	Address1_Line1 string,
	Address1_Line2 string,
	Address1_Line3 string,
	Address1_Longitude float ,
	Address1_Name string,
	Address1_PostalCode string,
	Address1_PostOfficeBox string,
	Address1_PrimaryContactName string,
	Address1_ShippingMethodCode int ,
	Address1_StateOrProvince string,
	Address1_Telephone1 string,
	Address1_Telephone2 string,
	Address1_Telephone3 string,
	Address1_UPSZone string,
	Address1_UTCOffset int ,
	Address2_AddressTypeCode int ,
	Address2_City string,
	Address2_Composite string,
	Address2_Country string,
	Address2_County string,
	Address2_AddressId string ,
	Address2_Fax string,
	Address2_FreightTermsCode int ,
	Address2_Latitude float ,
	Address2_Line1 string,
	Address2_Line2 string,
	Address2_Line3 string,
	Address2_Longitude float ,
	Address2_Name string,
	Address2_PostalCode string,
	Address2_PostOfficeBox string,
	Address2_PrimaryContactName string,
	Address2_ShippingMethodCode int ,
	Address2_StateOrProvince string,
	Address2_Telephone1 string,
	Address2_Telephone2 string,
	Address2_Telephone3 string,
	Address2_UPSZone string,
	Address2_UTCOffset int ,
	OwnerId string ,
	OwnerIdName string,
	OwnerIdYomiName string,
	OwnerIdDsc int ,
	OwnerIdType int ,
	OwningUser string ,
	OwningTeam string ,
	AccountId string ,
	AccountIdName string,
	AccountIdYomiName string,
	ParentContactId string ,
	ParentContactIdName string,
	ParentContactIdYomiName string,
	ContactId string ,
	DefaultPriceLevelId string ,
	CustomerSizeCode int ,
	CustomerTypeCode int ,
	PreferredContactMethodCode int ,
	LeadSourceCode int ,
	OriginatingLeadId string ,
	OwningBusinessUnit string ,
	PaymentTermsCode int ,
	ShippingMethodCode int ,
	ParticipatesInWorkflow binary ,
	IsBackofficeCustomer binary ,
	Salutation string,
	JobTitle string,
	FirstName string,
	Department string,
	NickName string,
	MiddleName string,
	LastName string,
	Suffix string,
	YomiFirstName string,
	FullName string,
	YomiMiddleName string,
	YomiLastName string,
	Anniversary timestamp ,
	BirthDate timestamp ,
	GovernmentId string,
	YomiFullName string,
	Description string,
	EmployeeId string,
	GenderCode int ,
	AnnualIncome decimal ,
	HasChildrenCode int ,
	EducationCode int ,
	WebSiteUrl string,
	FamilyStatusCode int ,
	FtpSiteUrl string,
	EMailAddress1 string,
	SpousesName string,
	AssistantName string,
	EMailAddress2 string,
	AssistantPhone string,
	EMailAddress3 string,
	DoNotPhone binary ,
	ManagerName string,
	ManagerPhone string,
	DoNotFax binary ,
	DoNotEMail binary ,
	DoNotPostalMail binary ,
	DoNotBulkEMail binary ,
	DoNotBulkPostalMail binary ,
	AccountRoleCode int ,
	TerritoryCode int ,
	IsPrivate binary ,
	CreditLimit decimal ,
	CreatedOn timestamp ,
	CreditOnHold binary ,
	CreatedBy string ,
	ModifiedOn timestamp ,
	ModifiedBy string ,
	NumberOfChildren int ,
	ChildrensNames string,
	VersionNumber timestamp ,
	MobilePhone string,
	Pager string,
	Telephone1 string,
	Telephone2 string,
	Telephone3 string,
	Fax string,
	Aging30 decimal ,
	StateCode int ,
	Aging60 decimal ,
	StatusCode int ,
	Aging90 decimal ,
	PreferredSystemUserId string ,
	PreferredServiceId string ,
	MasterId string ,
	PreferredAppointmentDayCode int ,
	PreferredAppointmentTimeCode int ,
	DoNotSendMM binary ,
	ParentCustomerId string ,
	Merged binary ,
	ExternalUserIdentifier string,
	SubscriptionId string ,
	PreferredEquipmentId string ,
	LastUsedInCampaign timestamp ,
	ParentCustomerIdName string,
	ParentCustomerIdType int ,
	TransactionCurrencyId string ,
	OverriddenCreatedOn timestamp ,
	ExchangeRate decimal,
	ImportSequenceNumber int ,
	TimeZoneRuleVersionNumber int ,
	UTCConversionTimeZoneCode int ,
	AnnualIncome_Base decimal ,
	CreditLimit_Base decimal ,
	Aging60_Base decimal ,
	Aging90_Base decimal ,
	Aging30_Base decimal ,
	ParentCustomerIdYomiName string,
	CreatedOnBehalfBy string ,
	ModifiedOnBehalfBy string ,
	IsAutoCreate binary ,
	StageId string ,
	ProcessId string ,
	EntityImageId string ,
	mbs_ContactType int ,
	mbs_countryid string ,
	mbs_PartnerId string ,
	mbs_stateid string ,
	mbs_crmrecorduniqueid string,
	mbs_donotemail int ,
	mbs_donotmail int ,
	mbs_donotpartneremail int ,
	mbs_donotpartnermail int ,
	mbs_donotpartnerphone int ,
	mbs_donotphone int ,
	mbs_globaloptout binary ,
	mbs_individualnativeid string,
	mbs_puid string,
	mbs_gsxcontactid string,
	mbs_preferredlanguageid string 

	)

ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'
LOCATION 'wasb://crmrcluster@crmrstorage.blob.core.windows.net/ContactData';
