DROP TABLE leadtable;
CREATE EXTERNAL TABLE leadtable
(
	mbs_prefferedlanguageidName string,
	mbs_contactIdName string,
	mbs_currentsalesteamIdName string,
	TransactionCurrencyIdName string,
	CreatedByYomiName string,
	mbs_ProductIdName string,
	mbs_industryidName string,
	ModifiedByName string,
	mbs_ParentCustomerIdName string,
	mbs_SalesSubDistrictIdName string,
	CreatedOnBehalfByName string,
	mbs_subscriptionidName string,
	ParentContactIdYomiName string,
	ModifiedOnBehalfByName string,
	ParentContactIdName string,
	mbs_partneridName string,
	ModifiedByYomiName string,
	mbs_ParentCustomerIdYomiName string,
	mbs_countryidName string,
	mbs_promocodeidName string,
	mbs_originatingsalesteamIdYomiName string,
	CampaignIdName string,
	CreatedByName string,
	mbs_currentsalesteamIdYomiName string,
	mbs_stateidName string,
	ParentAccountIdYomiName string,
	EntityImage string ,
	EntityImage_Timestamp bigint ,
	mbs_contactIdYomiName string,
	CreatedOnBehalfByYomiName string,
	mbs_originatingsalesteamIdName string,
	mbs_referredpartneridName string,
	MasterLeadIdName string,
	EntityImage_URL string,
	mbs_SalesDistrictIdName string,
	OriginatingCaseIdName string ,
	MasterLeadIdYomiName string,
	QualifyingOpportunityIdName string,
	ModifiedOnBehalfByYomiName string,
	ParentAccountIdName string,
	Address1_AddressTypeCode int ,
	Address1_City string,
	Address1_Composite string,
	Address1_Country string,
	Address1_County string,
	Address1_Fax string,
	Address1_Latitude float ,
	Address1_AddressId string ,
	Address1_Line1 string,
	Address1_Line2 string,
	Address1_Line3 string,
	Address1_Longitude float ,
	Address1_Name string,
	Address1_PostalCode string,
	Address1_PostOfficeBox string,
	Address1_ShippingMethodCode int ,
	Address1_StateOrProvince string,
	Address1_Telephone1 string,
	Address1_Telephone2 string,
	Address1_Telephone3 string,
	Address1_UPSZone string,
	Address1_UTCOffset int ,
	Address2_AddressTypeCode int ,
	Address2_City string,
	Address2_Composite string,
	Address2_Country string,
	Address2_County string,
	Address2_Fax string,
	Address2_Latitude float ,
	Address2_AddressId string ,
	Address2_Line1 string,
	Address2_Line2 string,
	Address2_Line3 string,
	Address2_Longitude float ,
	Address2_Name string,
	Address2_PostalCode string,
	Address2_PostOfficeBox string,
	Address2_ShippingMethodCode int ,
	Address2_StateOrProvince string,
	Address2_Telephone1 string,
	Address2_Telephone2 string,
	Address2_Telephone3 string,
	Address2_UPSZone string,
	Address2_UTCOffset int ,
	OwnerId string ,
	OwnerIdName string,
	OwnerIdYomiName string,
	OwnerIdDsc int ,
	OwnerIdType int ,
	OwningUser string ,
	OwningTeam string ,
	AccountId string ,
	AccountIdName string,
	AccountIdYomiName string,
	ContactId string ,
	ContactIdName string,
	ContactIdYomiName string,
	LeadId string ,
	LeadSourceCode int ,
	LeadQualityCode int ,
	PriorityCode int ,
	IndustryCode int ,
	PreferredContactMethodCode int ,
	SalesStageCode int ,
	OwningBusinessUnit string ,
	Subject string,
	ParticipatesInWorkflow binary ,
	Description string,
	EstimatedValue float ,
	EstimatedCloseDate string ,
	CompanyName string,
	FirstName string,
	MiddleName string,
	LastName string,
	Revenue decimal ,
	NumberOfEmployees int ,
	DoNotPhone binary ,
	SIC string,
	DoNotFax binary ,
	EMailAddress1 string,
	JobTitle string,
	Salutation string,
	DoNotEMail binary ,
	EMailAddress2 string,
	DoNotPostalMail binary ,
	EMailAddress3 string,
	FullName string,
	YomiFirstName string,
	WebSiteUrl string,
	Telephone1 string,
	Telephone2 string,
	Telephone3 string,
	CreatedOn string ,
	IsPrivate binary ,
	Fax string,
	YomiMiddleName string,
	YomiLastName string,
	CreatedBy string ,
	ModifiedOn string ,
	ModifiedBy string ,
	YomiFullName string,
	MobilePhone string,
	StateCode int ,
	Pager string,
	StatusCode int ,
	VersionNumber timestamp ,
	CustomerId string ,
	CustomerIdName string,
	CustomerIdType int ,
	MasterId string ,
	CampaignId string ,
	DoNotSendMM binary ,
	Merged binary ,
	DoNotBulkEMail binary ,
	LastUsedInCampaign string ,
	TransactionCurrencyId string ,
	TimeZoneRuleVersionNumber int ,
	UTCConversionTimeZoneCode int ,
	ImportSequenceNumber int ,
	OverriddenCreatedOn string ,
	ExchangeRate decimal,
	EstimatedAmount decimal ,
	EstimatedAmount_Base decimal ,
	Revenue_Base decimal ,
	YomiCompanyName string,
	CustomerIdYomiName string,
	CreatedOnBehalfBy string ,
	ModifiedOnBehalfBy string ,
	IsAutoCreate binary ,
	ParentAccountId string ,
	ParentContactId string ,
	RelatedObjectId string ,
	BudgetAmount decimal ,
	BudgetAmount_Base decimal ,
	BudgetStatus int ,
	DecisionMaker binary ,
	Need int ,
	PurchaseTimeFrame int ,
	EvaluateFit binary ,
	InitialCommunication int ,
	ConfirmInterest binary ,
	PurchaseProcess int ,
	SalesStage int ,
	ScheduleFollowUp_Prospect string ,
	ScheduleFollowUp_Qualify string ,
	QualificationComments string,
	QualifyingOpportunityId string ,
	StageId string ,
	ProcessId string ,
	EntityImageId string ,
	OriginatingCaseId string ,
	mbs_BDMContact int ,
	mbs_BornOnDate string ,
	mbs_Budget decimal ,
	mbs_budget_Base decimal ,
	mbs_CurrentStatus int ,
	mbs_CustomerSourceID string,
	mbs_EndDate string ,
	mbs_EstimatedNoOfSeats int ,
	mbs_gsxid string,
	mbs_HasBudget binary ,
	mbs_IsDecisionMaker binary ,
	mbs_LeadAssignmentEmailSent binary ,
	mbs_LeadCountry int ,
	mbs_LeadTopic string,
	mbs_LedBy string,
	mbs_mioid string,
	mbs_OfferType string,
	mbs_OriginatingOnlineSubscription string,
	mbs_PartnerEngagement string,
	mbs_PCCountTotalOrg int ,
	mbs_PreferredLanguage string,
	mbs_PreferredLanguageChoice int ,
	mbs_Product int ,
	mbs_Saluation int ,
	mbs_Segment int ,
	mbs_SolutionNeed binary ,
	mbs_StartDate string ,
	mbs_StateProvidence int ,
	mbs_Subsegment int ,
	mbs_TimetoPurchase int ,
	mbs_TransferAgencyName string,
	mbs_UserLicensesPurchased int ,
	mbs_WWLMResponseID string,
	mbs_ParentCustomerId string ,
	mbs_contactId string ,
	mbs_countryid string ,
	mbs_partnerid string ,
	mbs_referredpartnerid string ,
	mbs_SalesDistrictId string ,
	mbs_SalesSubDistrictId string ,
	mbs_stateid string ,
	mbs_ProductId string ,
	mbs_activityinfo string,
	mbs_businesspriority string,
	mbs_crmcontactid string,
	mbs_donotemail int ,
	mbs_donotmail int ,
	mbs_donotpartneremail int ,
	mbs_donotpartnermail int ,
	mbs_donotpartnerphone int ,
	mbs_donotphone int ,
	mbs_globalallowemail binary ,
	mbs_globalallowphone binary ,
	mbs_globaloptout binary ,
	mbs_indworkphone string,
	mbs_orgworkphone string,
	mbs_partnerallowemail binary ,
	mbs_partnerallowphone binary ,
	mbs_partnerattachdate string ,
	mbs_partneroptout binary ,
	mbs_phonecontactstatus int ,
	mbs_topquestionsandconcerns string,
	mbs_prefferedlanguageid string ,
	mbs_subscriptionid string ,
	mbs_leadsource string,
	mbs_partnerofrecord string,
	mbs_promocodeid string ,
	mbs_crmrecorduniqueid string,
	mbs_leadtype int ,
	mbs_puid string,
	mbs_tenantid string,
	mbs_dunsnumber string,
	mbs_parentproduct string,
	mbs_industryid string ,
	mbs_customerindicatedpartner string,
	mbs_salesteam string,
	mbs_originalsubmittingsubsidiary string,
	mbs_currentsalesteamId string ,
	mbs_originatingsalesteamId string ,
	mbs_mssalestpid string,
	mbs_pcdevicestotal int ,
	mbs_gsxleadid string,
	mbs_needsummary string,
	mbs_migrationnotes string )

ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'
LOCATION 'wasb://crmrcluster@crmrstorage.blob.core.windows.net/LeadData';
